model:
  features: [32, 32, 32, 16]  # MLP features

training:
  learning_rate: 0.0001
  epochs: 100000
  batch_size: 32

ode:
  b: 0.3   # Damping coefficient
  m: 1.0   # Mass
  l: 1.0   # Length
  g: 9.81  # Gravity
